api_platform:
  title: 'eXeLearning API (experimental)'
  version: '2.0'
  formats:
    json: [ 'application/json' ]
    jsonld: [ 'application/ld+json' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [3]
    api_keys:
      JWT:
        name: Authorization
        type: header

  http_cache:
    invalidation:
      enabled: false
  mapping:
    paths:
      - '%kernel.project_dir%/src'
  enable_swagger_ui: true
  enable_re_doc: true
  enable_entrypoint: true
  enable_docs: true
