# config/packages/framework.yaml

# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_probability: null

    #esi: true
    #fragments: true
    php_errors:
        log: true

    error_controller: App\Controller\net\exelearning\Controller\ErrorController::show

    # https://symfony.com/doc/5.4/deployment/proxies.html
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

    cache:
        # The path where the cache will be stored.
        directory: '%app.cache.dir%'
        app: cache.adapter.array      # Use in-memory cache that is not persisted
        system: cache.adapter.array   # Use in-memory cache for the system
    router:
        strict_requirements: null     # Disable the cache for dynamic routes

    assets:
        base_path: 'assets/%app.version%'  # Base path for assets based on version for avoid cache

parameters:
    default_cache_dir: '%kernel.project_dir%/var/cache'
