# ⚠️ WARNING: This docker-compose file is mainly intended for development.
# For production deployments, please use the example docker-compose files
# provided in doc/deploy/ (examples available for SQLite, MariaDB and PostgreSQL).
---
services:

  exelearning:
    build: .
    container_name: exelearning
    hostname: exelearning # Important! To be called from chrome container
    env_file:
      - .env.dist
      - .env # Overrides what is defined in .env
    ports:
      - ${APP_PORT}:8080 # Maps the host's $APP_PORT to the container's port 8080
      # - 9003:9003 # Port for Xdebug, you don't need to map this port, because is the container who connects to the host xdebug
    restart: unless-stopped # Restart the container unless it is stopped manually
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./public:/app/public
      - ./translations:/app/translations
      - ./templates:/app/templates
      - ./config:/app/config
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - mnt-data:/mnt/data:rw # Mount the volume for persistent data
      - ./e2e_screenshots:/tmp/e2e_screenshots
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET_KEY}
      PRE_CONFIGURE_COMMANDS:
      POST_CONFIGURE_COMMANDS: |
        echo "this is a test line 1"
        echo "this is a test line 2"
        php bin/console app:create-user ${TEST_USER_EMAIL} ${TEST_USER_PASSWORD} ${TEST_USER_USERNAME} --no-fail

  # The alpine-chromium image includes a browser configured to work with Chromedriver  
  chrome:
    image: ghcr.io/erseco/alpine-chromedriver
    container_name: chrome
    hostname: chrome # Important! To be called from exelearning container
    shm_size: "2gb"
    # ports:
    #   - "9515:9515" # Whe don't really need to expose ports
    profiles:
      - e2e # Container only will be started with --profile e2e option
    volumes:
      - ./tests/Fixtures:/app/tests/Fixtures # Mount the SAME Fixtures directory


volumes:
  mnt-data:
